---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cliente2-dev-deployment
  namespace: cliente2-dev-ns
  labels:
    customer: cliente2
    app: flask
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      customer: cliente2
      app: flask
      env: dev
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        customer: cliente2
        app: flask
        env: dev
    spec:
      containers:
      - name: client2-dev-web
        image: djoven89/app-lab2:1.0.0
        ports:
        - containerPort: 8080
          name: web-port
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
