---
kind: Service
apiVersion: v1
metadata:
  name: cliente2-prod-service
  namespace: cliente2-prod-ns
  labels:
    customer: cliente2
    app: flask
    env: prod
spec:
  selector:
    customer: cliente2
    app: flask
    env: prod
    version: 1.0.0
  type:  NodePort
  ports:
  - name: cliente2-prod-web-port
    port: 8080
    targetPort: 8080
    nodePort: 32022
