# Crea un pod llamado db-test cuya imagen sea mysql:8.0 que exponga el puerto 3306 y que use las siguientes variables obteniendo su valor del secret secret-db-test-conf y
# y de secret-db-test-name.
#   MYSQL_ROOT_PASSWORD
#   MYSQL_USER
#   MYSQL_PASSWORD
#   MYSQL_DATABASE

###
# CLI
###

# kubectl run db-test --image mysql:8.0 --port 3306 --dry-run -o yaml
# kubectl exec -ti db-test -- sh -c 'env' | egrep '(USER|PASSWORD)'

###
# YAML
###

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: db-test
  name: db-test
spec:
  containers:
  - image: mysql:8.0
    name: db-test
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-db-test-conf
          key: APP_ROOT_PWD
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: secret-db-test-conf
          key: APP_DBA_USERNAME
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret-db-test-conf
          key: APP_DBA_PWD
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: secret-db-test-name
          key: APP_DB_NAME
    resources: {}
  restartPolicy: Always
