---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-mysql
  labels:
    volumename: vol02
    app: wordpress
    tier: mysql
    version: 1.0.0
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-mysql
  nfs:
    path: /srv/lv_vol02
    server: 192.168.100.10

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-apache
  labels:
    volumename: vol01
    app: wordpress
    tier: apache
    version: 1.0.0
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-apache
  nfs:
    path: /srv/lv_vol01
    server: 192.168.100.10
