# Elimina el contener cli del deployment.

###
# CLI
###

# kubectl get deployments.apps deployment-website -o yaml
# (alternativa) kubectl edit deployment deployment-website
# kubectl get deployments,pods -o wide
# kubectl describe pod/deployment-website-fc66d4797-5lcfr | egrep -i image:


###
# YAML
###

apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"4","kubernetes.io/change-cause":"image learnk8s/app:1.0.0"},"creationTimestamp":"2024-10-20T17:17:48Z","generation":6,"labels":{"app":"deployment-website","env":"staging"},"name":"deployment-website","namespace":"default","resourceVersion":"93300","uid":"6d810e7d-70bc-4e09-b803-53b6295d1cd0"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"deployment-website"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2024-10-20T19:29:04+02:00"},"creationTimestamp":null,"labels":{"app":"deployment-website"}},"spec":{"containers":[{"image":"learnk8s/app:1.0.0","imagePullPolicy":"IfNotPresent","name":"app","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"},{"args":["-f","/dev/null"],"command":["tail"],"image":"alpine/curl","name":"cli","resources":{}}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2024-10-20T17:17:54Z","lastUpdateTime":"2024-10-20T17:17:54Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2024-10-20T17:17:48Z","lastUpdateTime":"2024-10-20T17:29:07Z","message":"ReplicaSet \"deployment-website-5b58cddb79\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":6,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
    kubernetes.io/change-cause: image learnk8s/app:1.0.0
  creationTimestamp: "2024-10-20T17:17:48Z"
  generation: 10
  labels:
    app: deployment-website
    env: staging
  name: deployment-website
  namespace: default
  resourceVersion: "94182"
  uid: 6d810e7d-70bc-4e09-b803-53b6295d1cd0
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deployment-website
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-10-20T19:29:04+02:00"
      creationTimestamp: null
      labels:
        app: deployment-website
    spec:
      containers:
      - image: learnk8s/app:3.0.0
        imagePullPolicy: IfNotPresent
        name: app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2024-10-20T17:17:54Z"
    lastUpdateTime: "2024-10-20T17:17:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-10-20T17:17:48Z"
    lastUpdateTime: "2024-10-20T17:38:50Z"
    message: ReplicaSet "deployment-website-6444fd8f99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3